# Generated by Django 3.1.5 on 2022-05-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя игрока')),
                ('result', models.IntegerField(verbose_name='Результат')),
                ('game_move', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial_game.table')),
            ],
        ),
    ]
