# Generated by Django 3.1.5 on 2022-05-19 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_game', '0003_auto_20220519_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='grants',
            field=models.IntegerField(default=0, verbose_name='Гранты'),
        ),
        migrations.AddField(
            model_name='table',
            name='other_invest',
            field=models.IntegerField(default=0, verbose_name='Другие расходы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
