# Generated by Django 3.1.6 on 2022-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0004_auto_20220520_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blue_card',
            name='count',
        ),
        migrations.RemoveField(
            model_name='blue_card',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='blue_card',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='blue_card',
            name='price_3',
        ),
        migrations.AddField(
            model_name='blue_card',
            name='ads_percent',
            field=models.PositiveIntegerField(default=2, verbose_name='Проценты на SMM'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='detector_percent',
            field=models.PositiveIntegerField(default=15, verbose_name='Процент, на кот. выросла цена датчиков'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='education',
            field=models.PositiveIntegerField(default=12000, verbose_name='Стоимость обучения сотрудника'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='equip',
            field=models.PositiveIntegerField(default=30000, verbose_name='Цена доп. оборудования'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='fines',
            field=models.PositiveIntegerField(default=1000, verbose_name='Штраф'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='fired_percent',
            field=models.PositiveIntegerField(default=50, verbose_name='Процент от оклада сотруднику, выполняющему обязательства другого'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='hospitality_1',
            field=models.PositiveIntegerField(default=5000, verbose_name='Стоимость стенда'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='hospitality_2',
            field=models.PositiveIntegerField(default=1000, verbose_name='Стоимость флаеров'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='hospitality_3',
            field=models.PositiveIntegerField(default=15000, verbose_name='Стоимость места на выставке'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='online_shop',
            field=models.PositiveIntegerField(default=50000, verbose_name='Цена онлайн-магазина'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='price_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Процент, на кот. выросла цена продукта'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='registration',
            field=models.PositiveIntegerField(default=5000, verbose_name='Цена регистрации компании'),
        ),
        migrations.AddField(
            model_name='blue_card',
            name='salary_num',
            field=models.PositiveIntegerField(default=50000, verbose_name='Премия программистам'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='salary_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Процент премии сотрудникам'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='count_1',
            field=models.IntegerField(verbose_name='Кол-во товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='count_2',
            field=models.IntegerField(verbose_name='Кол-во товара в следующем месяце'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='discount',
            field=models.IntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='earnings',
            field=models.IntegerField(verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='percent',
            field=models.IntegerField(verbose_name='Процент онлайн магазина'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
    ]
