# Generated by Django 3.1.5 on 2022-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0013_auto_20220522_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bluecard',
            old_name='ads_percent',
            new_name='ads',
        ),
    ]
