# Generated by Django 4.0.4 on 2022-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0022_true_table_funds_refund2'),
    ]

    operations = [
        migrations.AddField(
            model_name='true_table',
            name='investflag',
            field=models.BooleanField(default=False, verbose_name='Флаг привлечения инвестиций'),
        ),
    ]
