# Generated by Django 4.0.4 on 2022-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0023_auto_20220524_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='true_table',
            name='grants',
            field=models.FloatField(default=0, verbose_name='Дополнительная переменная, для хранения суммы гранта'),
        ),
        migrations.AddField(
            model_name='true_table',
            name='investflag',
            field=models.BooleanField(default=False, verbose_name='Флаг привлечения инвестиций'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='true_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
