# Generated by Django 4.0.4 on 2022-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0023_true_table_investflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='true_table',
            name='grants',
            field=models.FloatField(default=0, verbose_name='Дополнительная переменная, для хранения суммы гранта'),
        ),
    ]
