# Generated by Django 3.1.5 on 2022-05-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blue_card',
            options={'verbose_name': 'Голубая карта', 'verbose_name_plural': 'Голубые карты'},
        ),
        migrations.AlterModelOptions(
            name='green_card',
            options={'verbose_name': 'Зеленая карта', 'verbose_name_plural': 'Зеленые карты'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Таблица хода', 'verbose_name_plural': 'Таблицы хода'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='game_move',
        ),
        migrations.AddField(
            model_name='table',
            name='cash_balance_begin',
            field=models.IntegerField(default=10000, verbose_name='Остаток денежных средств на начало'),
        ),
        migrations.AddField(
            model_name='table',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial_game.user'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='count',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='price_1',
            field=models.IntegerField(verbose_name='цена 1'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='price_2',
            field=models.IntegerField(verbose_name='цена 2'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='price_3',
            field=models.IntegerField(verbose_name='цена 3'),
        ),
        migrations.AlterField(
            model_name='blue_card',
            name='salary_percent',
            field=models.IntegerField(verbose_name='процент премии сотрудникам'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='count_1',
            field=models.IntegerField(verbose_name='Кол-во 1 товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='count_2',
            field=models.IntegerField(verbose_name='Кол-во 1 товара в следующем месяце'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='discount',
            field=models.IntegerField(verbose_name='процент скидки'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='earnings',
            field=models.IntegerField(verbose_name='выручка'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='percent',
            field=models.IntegerField(verbose_name='процент онлайн магазина'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='price_1',
            field=models.IntegerField(verbose_name='Цена 1 товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='green_card',
            name='price_2',
            field=models.IntegerField(verbose_name='Цена 1 товара в следующем месяце'),
        ),
        migrations.AlterField(
            model_name='table',
            name='ads',
            field=models.IntegerField(default=0, verbose_name='Расходы на рекламу'),
        ),
        migrations.AlterField(
            model_name='table',
            name='cash_balance_end',
            field=models.IntegerField(default=0, verbose_name='Остаток денежных средств на конец'),
        ),
        migrations.AlterField(
            model_name='table',
            name='cash_flow',
            field=models.IntegerField(default=0, verbose_name='Денежный поток'),
        ),
        migrations.AlterField(
            model_name='table',
            name='cost_price',
            field=models.IntegerField(default=700, verbose_name='Себестоимость продукции'),
        ),
        migrations.AlterField(
            model_name='table',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='table',
            name='current_costs',
            field=models.IntegerField(default=0, verbose_name='Текущие расходы всего'),
        ),
        migrations.AlterField(
            model_name='table',
            name='earning_taxes',
            field=models.IntegerField(default=0, verbose_name='Общая SUM налогов (6% *Итого Доходов)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='table',
            name='education',
            field=models.IntegerField(default=0, verbose_name='Обучение сотрудников'),
        ),
        migrations.AlterField(
            model_name='table',
            name='equip',
            field=models.IntegerField(default=0, verbose_name='Закупка оборудования'),
        ),
        migrations.AlterField(
            model_name='table',
            name='fin_res',
            field=models.IntegerField(default=0, verbose_name='Финансовый результат (прибыль/убыток)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='funding',
            field=models.IntegerField(default=0, verbose_name='Финансирование'),
        ),
        migrations.AlterField(
            model_name='table',
            name='funds_receipt',
            field=models.IntegerField(default=0, verbose_name='Заёмные средства (поступления)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='funds_refund',
            field=models.IntegerField(default=0, verbose_name='Заёмные средства (возврат)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='hospitality',
            field=models.IntegerField(default=0, verbose_name='Представительские расходы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='investments',
            field=models.IntegerField(default=0, verbose_name='Инвестиционные расходы всего'),
        ),
        migrations.AlterField(
            model_name='table',
            name='month_num',
            field=models.IntegerField(default=1, verbose_name='Номер месяца'),
        ),
        migrations.AlterField(
            model_name='table',
            name='other',
            field=models.IntegerField(default=0, verbose_name='Другие расходы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='own_funds',
            field=models.IntegerField(default=0, verbose_name='Собственные средства основателей'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='table',
            name='rent_pay',
            field=models.IntegerField(default=10000, verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='table',
            name='research',
            field=models.IntegerField(default=0, verbose_name='Проведение научных исследований'),
        ),
        migrations.AlterField(
            model_name='table',
            name='salary',
            field=models.IntegerField(default=30000, verbose_name='Зарплата сотрудников'),
        ),
        migrations.AlterField(
            model_name='table',
            name='salary_taxes',
            field=models.IntegerField(default=0, verbose_name='Начисления на заработную плату сотрудников'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sponsor_invest',
            field=models.IntegerField(default=0, verbose_name='Инвестиции'),
        ),
        migrations.AlterField(
            model_name='table',
            name='tech',
            field=models.IntegerField(default=0, verbose_name='Приобретение технологий'),
        ),
        migrations.AlterField(
            model_name='table',
            name='third_party',
            field=models.IntegerField(default=0, verbose_name='Услуги сторонних организаций'),
        ),
        migrations.AlterField(
            model_name='user',
            name='result',
            field=models.IntegerField(default=0, verbose_name='Результат'),
        ),
    ]
