# Generated by Django 3.1.6 on 2022-05-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0006_auto_20220521_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Описание')),
                ('card_type', models.CharField(choices=[('products', 'Выпуск продукции 1 мес'), ('sale', 'Распродажа'), ('earnings', 'Выручка'), ('opt_1', 'Оптовый контрак 1 мес'), ('opt_2', 'Оптовый контрак 2 мес'), ('online', 'Онлайн заказы')], max_length=15, verbose_name='Тип карты')),
                ('count_1', models.IntegerField(verbose_name='Кол-во товара в этом месяце')),
                ('price_1', models.IntegerField(verbose_name='Цена 1 товара в этом месяце')),
                ('earnings', models.IntegerField(verbose_name='Выручка')),
                ('discount', models.IntegerField(verbose_name='Процент скидки')),
                ('count_2', models.IntegerField(verbose_name='Кол-во товара в следующем месяце')),
                ('price_2', models.IntegerField(verbose_name='Цена 1 товара в следующем месяце')),
                ('percent', models.IntegerField(verbose_name='Процент онлайн магазина')),
            ],
            options={
                'verbose_name': 'Зеленая карта',
                'verbose_name_plural': 'Зеленые карты',
            },
        ),
        migrations.RenameModel(
            old_name='blue_card',
            new_name='BlueCard',
        ),
        migrations.DeleteModel(
            name='green_card',
        ),
    ]
