# Generated by Django 3.1.6 on 2022-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0008_auto_20220522_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluecard',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='bluecard',
            name='salary_num',
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='ads_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Проценты на SMM'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='card_type',
            field=models.CharField(choices=[('bonus', 'Бонус к зарплате'), ('fines', 'Штрафы (налоги, регистрация)'), ('online_shop', 'Покупка онлайн-магазина'), ('ads', 'Траты на рекламу (СММ)'), ('equip', 'Закупка оборудования'), ('fired', 'Уволился 1 программист'), ('detector', 'Повышение цен на компоненты'), ('education', 'Доп. обучение сотрудников'), ('hospitality', 'Выставка')], max_length=15, verbose_name='Тип карты'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='detector_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент, на кот. выросла цена датчиков'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='education',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость обучения сотрудника'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='equip',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доп. оборудования'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='fines',
            field=models.PositiveIntegerField(default=0, verbose_name='Штраф'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='fired_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент от оклада сотруднику, выполняющему обязательства другого'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='hospitality_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость стенда'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='hospitality_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость флаеров'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='hospitality_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость места на выставке'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='online_shop',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена онлайн-магазина'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='price_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент, на кот. выросла цена продукта'),
        ),
        migrations.AlterField(
            model_name='bluecard',
            name='salary_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент премии сотрудникам'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='card_type',
            field=models.CharField(choices=[('products', 'Выпуск продукции 1 мес'), ('sale', 'Распродажа'), ('earnings', 'Выручка'), ('opt_1', 'Оптовый контракт 1 мес'), ('opt_2', 'Оптовый контракт 2 мес'), ('online', 'Онлайн заказы')], max_length=15, verbose_name='Тип карты'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='count_online',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='count_opt',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='count_opt_1',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='count_opt_2',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара в следующем месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='count_prod',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='earnings_opt',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='percents',
            field=models.IntegerField(default=0, verbose_name='Процент онлайн магазина'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='price_earn',
            field=models.IntegerField(default=0, verbose_name='Цена 1 товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='price_online',
            field=models.IntegerField(default=0, verbose_name='Цена 1 товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='price_opt_1',
            field=models.IntegerField(default=0, verbose_name='Цена 1 товара в этом месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='price_opt_2',
            field=models.IntegerField(default=0, verbose_name='Цена 1 товара в следующем месяце'),
        ),
        migrations.AlterField(
            model_name='greencard',
            name='price_prod',
            field=models.IntegerField(default=0, verbose_name='Цена 1 товара в этом месяце'),
        ),
    ]
