# Generated by Django 3.1.6 on 2022-05-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_game', '0010_table_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='true_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_salary', models.FloatField(default=10000, editable=False, verbose_name='')),
                ('def_employees', models.FloatField(default=3, editable=False, verbose_name='')),
                ('earnings', models.FloatField(default=0, verbose_name='Выручка')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во товара')),
                ('current_costs', models.FloatField(default=0, verbose_name='Текущ. расходы')),
                ('cost_price_per_one_detector', models.FloatField(default=0, verbose_name='Цена детектора')),
                ('cost_price_per_one_maket', models.FloatField(default=0, verbose_name='Цена макета')),
                ('cost_price', models.FloatField(default=0, verbose_name='Цена 1 товара')),
                ('employees', models.IntegerField(default=3, verbose_name='Кол-во работников')),
                ('salary', models.FloatField(default=models.FloatField(default=10000, editable=False, verbose_name=''), verbose_name='З/п 1-го работника')),
                ('salary_taxes', models.FloatField(default=0, verbose_name='Налог на зп')),
                ('need_in_third_party', models.BooleanField(default=True, verbose_name='Нужда в сторонней организации')),
                ('third_party_per_one', models.FloatField(default=200, verbose_name='Стор. орг. на 1 товар')),
                ('third_party', models.FloatField(default=0, verbose_name='Итог стор. орг.')),
                ('ads', models.FloatField(default=0, verbose_name='Реклама')),
                ('rent_pay', models.FloatField(default=10000, verbose_name='Аренда')),
                ('other', models.FloatField(default=0, verbose_name='Другие расходы')),
                ('earning_taxes', models.FloatField(default=0, verbose_name='Налог на прибыль')),
                ('new_provider', models.FloatField(default=1, verbose_name='Новый поставщик')),
                ('fin_res', models.FloatField(default=0, verbose_name='Фин. рез.')),
                ('investments', models.FloatField(default=0, verbose_name='Инвестиции')),
                ('equip', models.FloatField(default=0, verbose_name='Оборудование')),
                ('research', models.FloatField(default=0, verbose_name='Исследования')),
                ('tech', models.FloatField(default=0, verbose_name='Технологии')),
                ('education', models.FloatField(default=0, verbose_name='Обучение сотрудников')),
                ('hospitality', models.FloatField(default=0, verbose_name='Представительские расходы')),
                ('cash_balance_end', models.FloatField(default=0, verbose_name='Остаток денежных средств на конец')),
                ('next_month_count', models.IntegerField(default=0, verbose_name='Кол-во в след. мес.')),
                ('next_month_price', models.FloatField(default=0, verbose_name='Цена в след. мес.')),
                ('online_shop', models.BooleanField(default=False, verbose_name='')),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Итсинная таблица хода',
                'verbose_name_plural': 'Итсинные таблицы хода',
            },
        ),
    ]
