# Generated by Django 3.1.5 on 2022-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0014_auto_20220523_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='true_table',
            name='cash_flow',
            field=models.FloatField(default=0, verbose_name='Денежный поток'),
        ),
        migrations.AlterField(
            model_name='true_table',
            name='salary',
            field=models.FloatField(default=30000, verbose_name='З/п работников'),
        ),
    ]
