# Generated by Django 4.0.4 on 2022-05-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0017_user_mistakes_alter_bluecard_id_alter_greencard_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='fin_res_sum',
            field=models.FloatField(default=0, verbose_name='Сумма финансового результата'),
        ),
        migrations.AddField(
            model_name='table',
            name='own_funds_sum',
            field=models.FloatField(default=0, verbose_name='Сумма  средства основателей '),
        ),
    ]
