# Generated by Django 4.0.4 on 2022-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0018_table_fin_res_sum_table_own_funds_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='own_funds_sum',
            field=models.FloatField(default=0, verbose_name='Сумма собственных средств основателей '),
        ),
    ]
