# Generated by Django 4.0.4 on 2022-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_game', '0020_true_table_counterkred'),
    ]

    operations = [
        migrations.AddField(
            model_name='true_table',
            name='funds_refund',
            field=models.FloatField(default=0, verbose_name='Выплата банку'),
        ),
    ]
